name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt black isort pytest pytest-cov
    - name: Check code style with black
      run: black --check .
    - name: Check code style with isort
      run: isort --check .
    - name: Run tests with coverage
      run: pytest -q --cov=src
    - name: Upload coverage to Codecov
      run: |
        curl -s https://codecov.io/bash | bash 