[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[runner]
# Add these settings to help with package imports
magicEnabled = true
installTracer = true
fixMatplotlib = true 